/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kliinik;

import javax.swing.JOptionPane;
public class Klinik24 extends javax.swing.JFrame {

int biayaadmin, konsultasi, obat, diskon, totalharga, total;
    public Klinik24() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gjenispoli = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Umum = new javax.swing.JRadioButton();
        Gigi = new javax.swing.JRadioButton();
        Saraf = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NamaDokter = new javax.swing.JTextField();
        WaktuPraktek = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NomorPasien = new javax.swing.JTextField();
        NamaPasien = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LamaInap = new javax.swing.JTextField();
        NamaRuangan = new javax.swing.JComboBox<>();
        Harga = new javax.swing.JTextField();
        Discount = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Administrasi = new javax.swing.JCheckBox();
        Obat = new javax.swing.JCheckBox();
        Konsultasi = new javax.swing.JCheckBox();
        BiayaAdministrasi = new javax.swing.JTextField();
        BiayaObat = new javax.swing.JTextField();
        BiayaKonsultasi = new javax.swing.JTextField();
        Bersih = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("KLINIK 24 JAM HHH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 10, 160, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jenis Poli"));

        gjenispoli.add(Umum);
        Umum.setText("Umum");
        Umum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmumActionPerformed(evt);
            }
        });

        gjenispoli.add(Gigi);
        Gigi.setText("Gigi");
        Gigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GigiActionPerformed(evt);
            }
        });

        gjenispoli.add(Saraf);
        Saraf.setText("Saraf");
        Saraf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SarafActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Dokter");

        jLabel5.setText("Waktu Praktek");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Umum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Gigi)
                .addGap(85, 85, 85)
                .addComponent(Saraf)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(NamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WaktuPraktek)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Umum)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Saraf)
                        .addComponent(Gigi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(WaktuPraktek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(15, 45, 480, 190);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pasien"));

        jLabel6.setText("Nomor Pasien");

        jLabel7.setText("Nama Pasien");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NomorPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NomorPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(530, 80, 340, 129);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pilih Ruangan"));

        jLabel8.setText("Lama Inap");

        jLabel9.setText("Nama Ruangan");

        jLabel10.setText("Harga/Hari");

        jLabel11.setText("Discount");

        NamaRuangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilihan--", "Kenanga", "Mawar", "Melati", " " }));
        NamaRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaRuanganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LamaInap, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(108, 108, 108)
                        .addComponent(NamaRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(139, 139, 139)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LamaInap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NamaRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 270, 430, 200);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Perincian Biaya"));

        Administrasi.setText("Biaya Administrasi");
        Administrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministrasiActionPerformed(evt);
            }
        });

        Obat.setText("Biaya Obat");
        Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObatActionPerformed(evt);
            }
        });

        Konsultasi.setText("Biaya Konsultasi");
        Konsultasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonsultasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Administrasi)
                    .addComponent(Obat)
                    .addComponent(Konsultasi))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BiayaKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiayaObat, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiayaAdministrasi, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Administrasi)
                    .addComponent(BiayaAdministrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Obat)
                    .addComponent(BiayaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Konsultasi)
                    .addComponent(BiayaKonsultasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(480, 250, 410, 190);

        Bersih.setText("Bersih");
        Bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BersihActionPerformed(evt);
            }
        });
        getContentPane().add(Bersih);
        Bersih.setBounds(110, 530, 75, 29);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(230, 530, 77, 29);

        jLabel2.setText("Total");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 530, 36, 20);
        getContentPane().add(Total);
        Total.setBounds(450, 530, 200, 26);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\wallpaperflare.com_wallpaper.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -4, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmumActionPerformed
                if (Umum.isSelected()){
            NamaDokter.setText("Mahfud Effendi");
            WaktuPraktek.setText("Pagi");
        }

    }//GEN-LAST:event_UmumActionPerformed

    private void GigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GigiActionPerformed
                if(Gigi.isSelected()){
            NamaDokter.setText("Mutia Khasanah");
            WaktuPraktek.setText("Sore");
        }

    }//GEN-LAST:event_GigiActionPerformed

    private void SarafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SarafActionPerformed
                if (Saraf.isSelected()){
            NamaDokter.setText("Anisa Sulistyowati");
            WaktuPraktek.setText("Malam");
        }

    }//GEN-LAST:event_SarafActionPerformed

    private void NamaRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaRuanganActionPerformed
        if (NamaRuangan.getSelectedItem().equals("Kenanga")){
           Harga.setText("200000");
           int harga = Integer.parseInt(Harga.getText());
           int lama = Integer.parseInt(LamaInap.getText());
           int totalharga = harga * lama;
           int potongan1 = totalharga*10/100;
           int potongan2 = totalharga*0;
           
           if (lama >4){
               diskon = potongan1;
               Discount.setText(Integer.toString(potongan1));
               total = totalharga - diskon + biayaadmin + obat + konsultasi;
               Total.setText(String.valueOf(total));
           }
           else {
               diskon = potongan2;
               Discount.setText(Integer.toString(potongan2));
               total = totalharga - diskon + biayaadmin + obat + konsultasi;
               Total.setText(String.valueOf(total));
           }
       }
       else if (NamaRuangan.getSelectedItem().equals("Mawar")){
           Harga.setText("300000");
           int harga = Integer.parseInt(Harga.getText());
           int lama = Integer.parseInt(LamaInap.getText());
           int totalharga = harga * lama;
           int potongan1 = totalharga*10/100;
           int potongan2 = totalharga * 0;
           
           if (lama >4){
               diskon = potongan1;
               Discount.setText(Integer.toString(potongan1));
               total = totalharga - diskon + biayaadmin + obat + konsultasi;
               Total.setText(String.valueOf(total));
           }
           else {
               diskon = potongan2;
               Discount.setText(Integer.toString(potongan2));
               total = totalharga - diskon + biayaadmin + obat + konsultasi;
               Total.setText(String.valueOf(total));
           }
       }
              else if (NamaRuangan.getSelectedItem().equals("Melati")){
           Harga.setText("400000");
           int harga = Integer.parseInt(Harga.getText());
           int lama = Integer.parseInt(LamaInap.getText());
           int totalharga = harga * lama;
           int potongan1 = totalharga*10/100;
           int potongan2 = totalharga * 0;
           
           if (lama >4){
               diskon = potongan1;
               Discount.setText(Integer.toString(potongan1));
               total = totalharga - diskon + biayaadmin + obat + konsultasi;
               Total.setText(String.valueOf(total));
           }
           else {
               diskon = potongan2;
               Discount.setText(Integer.toString(potongan2));
               total = totalharga - diskon + biayaadmin + obat + konsultasi;
               Total.setText(String.valueOf(total));
           }
       }

    }//GEN-LAST:event_NamaRuanganActionPerformed

    private void AdministrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministrasiActionPerformed
        if (Administrasi.isSelected()){
            biayaadmin = 5000;
            BiayaAdministrasi.setText(String.valueOf(biayaadmin));
            int harga = Integer.parseInt(Harga.getText());
            int lama = Integer.parseInt(LamaInap.getText());
            int totaldiskon = Integer.parseInt(Discount.getText());
            total = (harga * lama) - totaldiskon + biayaadmin + konsultasi + obat;
            Total.setText(String.valueOf(total));
        }
        else {
            biayaadmin = 0;
            BiayaAdministrasi.setText(String.valueOf(biayaadmin));
            int harga = Integer.parseInt(Harga.getText());
            int lama = Integer.parseInt(LamaInap.getText());
            int totaldiskon = Integer.parseInt(Discount.getText());
            total = (harga * lama) - totaldiskon + biayaadmin + konsultasi + obat;
            Total.setText(String.valueOf(total));
        }

    }//GEN-LAST:event_AdministrasiActionPerformed

    private void ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObatActionPerformed
                if (Obat.isSelected()){
            obat = 50000;
            BiayaObat.setText(String.valueOf(obat));
            int harga = Integer.parseInt(Harga.getText());
            int lama = Integer.parseInt(LamaInap.getText());
            int totaldiskon = Integer.parseInt(Discount.getText());
            total = (harga * lama) - totaldiskon + biayaadmin + konsultasi + obat;
            Total.setText(String.valueOf(total));
        }
        else {
            obat = 0;
            BiayaObat.setText(String.valueOf(obat));
            int harga = Integer.parseInt(Harga.getText());
            int lama = Integer.parseInt(LamaInap.getText());
            int totaldiskon = Integer.parseInt(Discount.getText());
            total = (harga * lama) - totaldiskon + biayaadmin + konsultasi + obat;
            Total.setText(String.valueOf(total));
        }

    }//GEN-LAST:event_ObatActionPerformed

    private void KonsultasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonsultasiActionPerformed
               if (Konsultasi.isSelected()){
            konsultasi = 20000;
            BiayaKonsultasi.setText(String.valueOf(konsultasi));
            int harga = Integer.parseInt(Harga.getText());
            int lama = Integer.parseInt(LamaInap.getText());
            int totaldiskon = Integer.parseInt(Discount.getText());
            total = (harga * lama) - totaldiskon + biayaadmin + konsultasi + obat;
            Total.setText(String.valueOf(total));
        }
        else {
            konsultasi = 0;
            BiayaKonsultasi.setText(String.valueOf(konsultasi));
            int harga = Integer.parseInt(Harga.getText());
            int lama = Integer.parseInt(LamaInap.getText());
            int totaldiskon = Integer.parseInt(Discount.getText());
            total = (harga * lama) - totaldiskon + biayaadmin + konsultasi + obat;
            Total.setText(String.valueOf(total));
        }

    }//GEN-LAST:event_KonsultasiActionPerformed

    private void BersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BersihActionPerformed
        gjenispoli.clearSelection();
        Konsultasi.setSelected(false);
        BiayaKonsultasi.setText(null);
        Administrasi.setSelected(false);
        BiayaAdministrasi.setText(null);
        Obat.setSelected(false);
        BiayaObat.setText(null);
        NamaRuangan.setSelectedIndex(0);
        LamaInap.setText(null);
        Harga.setText(null);
        NamaDokter.setText(null);
        Discount.setText(null);
        Total.setText(null);
        NomorPasien.setText(null);
        NamaPasien.setText(null);
        WaktuPraktek.setText(null);
        NamaDokter.setText(null);

    }//GEN-LAST:event_BersihActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
            int answer = JOptionPane.showConfirmDialog(null, "konfirmasi keluar?", "informasi", JOptionPane.YES_NO_OPTION);
       if (answer == JOptionPane.YES_OPTION){
           dispose();
       }
       else{
           return;
       }

    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Klinik24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Klinik24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Klinik24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Klinik24.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Klinik24().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Administrasi;
    private javax.swing.JButton Bersih;
    private javax.swing.JTextField BiayaAdministrasi;
    private javax.swing.JTextField BiayaKonsultasi;
    private javax.swing.JTextField BiayaObat;
    private javax.swing.JTextField Discount;
    private javax.swing.JRadioButton Gigi;
    private javax.swing.JTextField Harga;
    private javax.swing.JButton Keluar;
    private javax.swing.JCheckBox Konsultasi;
    private javax.swing.JTextField LamaInap;
    private javax.swing.JTextField NamaDokter;
    private javax.swing.JTextField NamaPasien;
    private javax.swing.JComboBox<String> NamaRuangan;
    private javax.swing.JTextField NomorPasien;
    private javax.swing.JCheckBox Obat;
    private javax.swing.JRadioButton Saraf;
    private javax.swing.JTextField Total;
    private javax.swing.JRadioButton Umum;
    private javax.swing.JTextField WaktuPraktek;
    private javax.swing.ButtonGroup gjenispoli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
